### ISSUE TITLE
comile error

### ISSUE THREAD

**Issue by ishu0786** [LycaJB/LycaJB#1]
d /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Products/Debug-iphoneos/LycaJB.app/LycaJB normal arm64
    cd "/Users/ishaan/Desktop/my projects/LycaJB-master"
    export IPHONEOS_DEPLOYMENT_TARGET=11.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -L/Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Products/Debug-iphoneos -L/Users/ishaan/Desktop/my\ projects/LycaJB-master/multi_path/jelbrek -F/Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Products/Debug-iphoneos -filelist /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Intermediates.noindex/LycaJB.build/Debug-iphoneos/LycaJB.build/Objects-normal/arm64/LycaJB.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=11.3 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Intermediates.noindex/LycaJB.build/Debug-iphoneos/LycaJB.build/Objects-normal/arm64/LycaJB_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Intermediates.noindex/LycaJB.build/Debug-iphoneos/LycaJB.build/Objects-normal/arm64/LycaJB.swiftmodule -framework AVKit -weak-lz -weak_library /Users/ishaan/Desktop/my\ projects/LycaJB-master/multi_path/jelbrek/IOKit.tbd /Users/ishaan/Desktop/my\ projects/LycaJB-master/multi_path/jelbrek/qilin.o -Xlinker -dependency_info -Xlinker /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Intermediates.noindex/LycaJB.build/Debug-iphoneos/LycaJB.build/Objects-normal/arm64/LycaJB_dependency_info.dat -o /Users/ishaan/Library/Developer/Xcode/DerivedData/LycaJB-asfrgrpbwovepbaumfytsdjnuhlb/Build/Products/Debug-iphoneos/LycaJB.app/LycaJB

ld: warning: text-based stub file /Users/ishaan/Desktop/my projects/LycaJB-master/multi_path/jelbrek/IOKit.tbd and library file /Users/ishaan/Desktop/my projects/LycaJB-master/multi_path/jelbrek/IOKit.tbd are out of sync. Falling back to library file for linking.
Undefined symbols for architecture arm64:
  "_file_exist", referenced from:
      _patchSoftwareUpdateDaemon in jelbrek.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

unable to compile with above errors for iPhone X ios 11.3.1 
XCODE VERSION 9.3
![screenshot 2018-06-24 at 1 17 11 pm](https://user-images.githubusercontent.com/29410046/41817063-4aa400b2-77b1-11e8-8b58-e36a02e82e84.jpeg)

**Comment by LycaJB** [comment]
Hi! Sorry about that, I forgot to include that function. It is a simple fix, open `jelbrek.m` and go down to the setupBootstrap function, from that you'll see an if statement which checks if a file exists. Copy that if statement's logic and you should be good to go. Of course you'll need to update the file paths etc.

**Comment by jujijoog** [comment]
wtf does that mean? thats so confusing. could you elaborate?

you are talking about this right?

```
 if (!dbret) {
        NSFileManager *fileManager = [NSFileManager defaultManager];
        if (![fileManager fileExistsAtPath:@"/usr⁩/libexec⁩/cydia⁩/cydo"])
            printf("[INFO]: tar failed to extract and setup bootstrap :/");
        else
            printf("[INFO]: tar extracted and setup bootstrap!");
        launchAsPlatform((char*)[uicache UTF8String], NULL, NULL, NULL, NULL, NULL, NULL, NULL);
        launchAsPlatform((char*)[killall UTF8String], "-9", "springboardd", NULL, NULL, NULL, NULL, NULL);
    }
    else {
        printf("[INFO]: Well... Tar failed to extract bootstrap :/");
```

where exactly am i supposed to apply that logic and what am i changing paths to?
